package io.vaullet.common.web;

import org.jspecify.annotations.Nullable;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.bind.DefaultValue;

/**
 * The parts of the OpenAPI document that are prose rather than code.
 *
 * <p>Bound to {@code vaullet.openapi}. Everything else in the document — paths, schemas,
 * constraints — is generated by springdoc from the controllers, per ADR-011, §5's code-first
 * decision, and must not be configurable.
 *
 * @param title document title; defaults to {@code ${spring.application.name} API}
 * @param version the <em>major</em> API version as it appears in the URI (ADR-011, §2). Compatible
 *     additions do not change it; a breaking change means a new path major and a 12-month
 *     deprecation window
 * @param description free-form Markdown. A service-specific value should state the wire conventions
 *     a caller has to know; property placeholders resolve, so an environment label can be
 *     interpolated with {@code ${APP_ENVIRONMENT:unknown}}
 * @param contactName team accountable for the API
 * @param contactEmail how to reach them
 */
@ConfigurationProperties(prefix = "vaullet.openapi")
public record OpenApiProperties(
        @Nullable String title,
        @DefaultValue("1") String version,
        @Nullable String description,
        @DefaultValue("Platform team") String contactName,
        @DefaultValue("platform@vaullet.io") String contactEmail) {}
